" VIMRC

" Settings
"
set nocompatible
filetype plugin on
syntax on
" set encoding=utf-8
set number
set smartindent
set smartcase
set noswapfile
set nobackup
set incsearch

" Shortcuts/Remaps

" Split movement
nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>

map <C-o> :setlocal spell! spelllang=en_gb<CR>

" Todo Shortcut

autocmd BufWritePre * %s/\s\+$//e

